export const vars = {
  breakpoints: {
    onlyMobile: 'max-width: 786px',
  },
  styles: {
    sizes: {
      navigationWidth: '3.5rem',
      navigationMobileHeight: '3rem',
      footerRevealHeight: '5rem',
    },
    zIndices: {
      revealFooter: -10,
      mobileNavigationList: 10,
      mobileNavigationBar: 20,
    },
    fontSizes: {
      size0: '10px',
      size1: '12px',
      size2: '14px',
      size3: '16px',
      size4: '18px',
      size5: '20px',
      size6: '24px',
      size7: '30px',
      size8: '36px',
      size9: '48px',
      size10: '60px',
      size11: '72px',
      base: '20px',
    },
    colors: {
      white: '#FFFFFF',
      black: '#0C0C0C',
      neutral1: '#EEEFF1',
      neutral2: '#DDDDDD',
      neutral3: '#A7ABAF',
      neutral4: '#646C71',
      neutral5: '#4B5156',
      neutral6: '#3F474F',
      neutral7: '#292F34',
      accent1: '#EFF5F5',
      accent2: '#BEDEDB',
      accent3: '#9EDAD4',
      accent4: '#6EB9B3',
      accent5: '#32B0A6',
      accent6: '#048C81',
    },
    fontFamilies: {
      default: "'Open Sans', sans-serif",
      special: 'Futura, sans-serif',
    },
  },
}
